### ISSUE TITLE
Premake로 솔루션 생성시 부산물들의 디렉토리 지정

### ISSUE THREAD

**Issue by zxwnstn** [zxwnstn/AnrealEngine#2]
현재 Premake로 솔루션을 생성하면 소스가 있는 폴더에 부산물들이 생긴다.

부산물 목록
obj폴더, vxcproj, vcxproj.filters, vcxproj.user

이 부산물들이 생성되지 않게 하는것이 아니라, 생성되는 위치를 제어할수 있어야 한다.

**Comment by kiseop91** [comment]
확인
